# Generated by Django 4.2.10 on 2024-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_name',
            field=models.CharField(default='abc', max_length=25),
        ),
    ]
