# Generated by Django 3.1.1 on 2024-04-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_orderplaced_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
