# Generated by Django 3.1.1 on 2024-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20240404_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='customer',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Delivered', max_length=50),
        ),
    ]
