# Generated by Django 3.1.1 on 2024-04-05 05:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0006_auto_20240405_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Address',
        ),
    ]
